global:
  scrape_interval: 5s 

  external_labels:
    monitor: 'x4'

scrape_configs:
    # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'x4'
        # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8000']