{
 "title": "X4 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Game_Instance",
    "label": "Game loaded at:",
    "query": {
     "query": "label_values(X4_Player_Cash,Save)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "XL Ships",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "X4_Player_Ships{Size=\"XL\", Save=\"$Game_Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L Ships",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "X4_Player_Ships{Size=\"L\", Save=\"$Game_Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "M Ships",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "X4_Player_Ships{Size=\"M\", Save=\"$Game_Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S Ships",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "X4_Player_Ships{Size=\"S\", Save=\"$Game_Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cash",
   "type": "timeseries",
   "description": "X4 Player Cash",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "X4_Player_Cash{Save=\"$Game_Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}